### ISSUE TITLE
[Space] - SEO Solution

### ISSUE THREAD

**Issue by devformatters** [thematters/the-space#16]
tasks
- come up a SEO solution for space site

**Comment by tx0c** [comment]
SEO audit tools can give some advice:

1. https://pagespeed.web.dev/report?url=https://thespace.game
2. https://seositecheckup.com/seo-audit/thespace.game

the 1st thing we can do is to use `next/image`
```
Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn more](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=lr#images-without-dimensions)CLS
```
